platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

target 'GM' do
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxGesture'
pod 'Alamofire'
pod 'AlamofireImage'
pod 'AlamofireNetworkActivityIndicator'
pod 'RxAlamofire'
pod 'EVReflection'
pod 'EVReflection/Alamofire'
pod 'Hero'
end

post_install do |installer|
# List of Pods to use as Swift 3.2
myTargets = ['Hero']

installer.pods_project.targets.each do |target|
if myTargets.include? target.name
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '3.2'
end
end
end
end

